### ISSUE TITLE
Language setting is not working properly

### ISSUE THREAD

**Issue by egofree71** [IsmAvatar/LateralGM#169]
I have a french version of Windows 7. If is set the language to english, the labels are still displayed in french.

**Comment by RobertBColton** [comment]
@IsmAvatar @egofree71 I am solving this once and for all. Java 7 has a global JVM override for it. We have long since dropped Java 6 support so I am going with this solution.
http://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#setDefault%28java.util.Locale%29

I will be removing all of the previously added ugly hacks and replacing the preference with a new one. It will ask the JVM for available locales and then print their display names in a new ComboBox. A warning label is added to mention that LGM may not have an existing translation for the selected locale. The layout is complete in my local copy and will be finished in the next LGM release.

![General Preferences Layout](https://cloud.githubusercontent.com/assets/3212801/10034745/7acc6efa-6161-11e5-94b5-9f03add7b9f0.png)

**Comment by RobertBColton** [comment]
Translations in the tree are broke again as of 1.8.7 according to @egofree71.

**Comment by RobertBColton** [comment]
Closing this one out as long resolved, and #429 remains open to cover the remaining issue with translating the primary tree nodes.

**Comment by RobertBColton** [comment]
Closing this one out as long resolved, and #429 remains open to cover the remaining issue with translating the primary tree nodes. I tested and verified that the original issue here, that setting the language override does not override the system locale, is in fact resolved. I installed the Danish Windows 10 translation, including signing out and back in again. When the LGM preferences are cleared they pick up the system locale as the current locale. If egofree then overrides it to English and restarts LGM, he will have nothing but English translations in LGM's UI as he correctly expected. This is also the behavior of the Godot game engine.

Here's a summary of everything we discussed and concluded in this issue.
* Colons on labels belong in the translation because some languages, like Chinese, have their own colon that embeds a space.
* Concatenation of localized strings should be handled with string interpolation or formatting in the translation. Some languages, like Arabic, are right to left, and that's also a reason to put the colons into the translation too.
* What was referred to as "Program Default" could also be considered the [region-neutral locale](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#ROOT) which is just more general than the locale-neutral locale.
* The [ResourceBundle](https://docs.oracle.com/javase/8/docs/api/java/util/ResourceBundle.html#getBundle-java.lang.String-java.util.Locale-java.lang.ClassLoader-) goes from the most specific locale to the most general and neutral locale.
* The language preference we have now using [Locale.setDefault()](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#setDefault-java.util.Locale-) overrides the system default locale.
* There is a [bug in Java 11/13/14](https://bugs.openjdk.java.net/browse/JDK-8233045) I have that makes JFileChooser ignore our locale preference, and is fixed for Java 14. What's funny is originally we had fixed this issue that egofree had with the new way of forcing the locale only for it to crop back up in a later JDK version.
* We do not postfix our "messages.properties" with "en_US" so that other languages with partially missing keys will fall back on displaying the English version. We've decided this is better than displaying the error key as we do when it can't be found at all even in English.
