### ISSUE TITLE
Action List Selection

### ISSUE THREAD

**Issue by egofree71** [IsmAvatar/LateralGM#170]
If you are doing a copy and several pastes one after the other in the actions list, all actions remain selected.

**Comment by JoshDreamland** [comment]
I personally like having things I paste be selected. If pasting twice selects both pastes, that sounds aggravating, though; a paste should clear the original selection, if it's not erasing it.

**Comment by RobertBColton** [comment]
Rusky thinks it's less normal and unusual to maintain the selection for paste but I still think I disagree. The reason being that "Insert Image" in almost any rich text editor will keep the image selected so you can move it around. So far this is all working just fine in master and the bug originally reported by egofree has been fixed, the old selection is replaced with the new selection in a paste now as I also feel it should be.

```<Rusky> 1) that's not paste 2) ms word has a cursor 3) even if it does select on paste it's still better to be able to be precise about where you paste
<Rusky> so regardless of what you do there, let me paste after the end and before the beginning without moving after the paste
<Rusky> annnnnnd good night
<Rusky> for real```

I think what @rpjohnst is suggesting is something along the lines of a text editor like cursor that would always be active for the list. I should note that GMS does it the way master currently works where when you paste it inserts directly before the selected action or appends to the end if none is selected.

**Comment by RobertBColton** [comment]
In lgm16b4 there is paste operation using the built-in action for CTRL-V that comes with the default transfer handler used on ActionList. This paste operation always appends to the end because it does not use the selected index when the import is not a drop (https://github.com/IsmAvatar/LateralGM/blob/stable/org/lateralgm/components/ActionList.java#L527). This is correctly accounted for in master. However the Swing framework's built in paste operation does in fact maintain the selection the selection as well, of everything pasted. So I will go with this approach for stable and for master.

**Comment by rpjohnst** [comment]
Inserting before the selection or appending on no selection accomplishes what I described, without a weird vertical cursor.

**Comment by RobertBColton** [comment]
Sigh, thank you, now I know that the current implementation is in fact correct.

**Comment by RobertBColton** [comment]
This is full corrected now in master and stable.
