### ISSUE TITLE
Action List Focus Policy/DND

### ISSUE THREAD

**Issue by egofree71** [IsmAvatar/LateralGM#171]
Within the objects window, if the actions list panel doesn't have the focus, the keyboards shortcuts don't work.
To reproduce the problem :  just open a new objects window, and add directly new actions. It will not work. You have to select an action in the actions list panel.

**Comment by RobertBColton** [comment]
Even with all of the above features now added. This is not that big of an issue, because it also exists in GM: Studio as I just tested in 1.4 the latest version and it also exists in every Swing program I can find.

I sort of consider this a Java/Swing bug because if you check the official drag and drop demo's, dragging into a text area gives it focus but dragging onto a list does not give it focus. I am not sure at this time how native Windows Forms or even GTK will behave. However I can say that I believe a nice solution to this problem is to make the action list request focus when a DND tile is dropped on it. We can not make cut/copy/paste be attached to the room editor because it should also work for the selected events (though I notice we have not added these shortcuts) it should also work for the name text field, so it cannot be global to the whole object frame. I think my proposed solution is a nice one, I will try to test Qt/GTK/or Windows Forms.

**Comment by RobertBColton** [comment]
I just finished testing Construct and the "Add Event" options on its toolbar does give it's version of an action list keyboard focus. Stencyl is written in some esoteric and fundamentally flawed Java GUI framework (like all the others) so ofc it doesn't give keyboard focus, it doesn't even show focused buttons.

![Construct 2 Drag & Drop](https://cloud.githubusercontent.com/assets/3212801/14448863/d5299cba-003a-11e6-8c9b-4a5600455a99.png)
