### ISSUE TITLE
instance_id for new objects in rooms is incorrect if there are gaps.

### ISSUE THREAD

**Issue by sorlok** [IsmAvatar/LateralGM#180]
Steps to reproduce:
1) Create a new project. Create 1 room and 1 object.
2) Create 10 instances of the object in the room.
3) Delete (right-click) instances 7,8,9.
4) Save, close the editor.
5) Re-open the editor and the project.
6) Create 4 instances of the object in the room. You will now have two instances with the same ID (the 10th object).

Any ideas?

**Comment by RobertBColton** [comment]
@sorlok If you do not mind I am going to close this actually because it is a duplicate of #82 but I think I may fix it in this next LGM release I am going to make within the next few months. I am linking the ticket still because you have the steps to reproduce it. It should be easy to fix, but we don't need two tickets.

**Comment by RobertBColton** [comment]
This was finally corrected in 1.8.7 by properly reading and writing the instance names in the GMX format. I was only able to reproduce sorlok's issue with the GMX file handlers. I also discovered that I was not updating the lastId properly which caused the issue.
