### ISSUE TITLE
Error openning 

### ISSUE THREAD

**Issue by lcnvdl** [IsmAvatar/LateralGM#215]
Operating System: Windows 7
Version: 6.1
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.7.0_51

Available processors (cores): 2
Free memory (bytes): 31609528
Maximum memory (bytes): 924844032
Total memory available to JVM (bytes): 79167488

File system root: C:\
Total space (bytes): 125724258304
Free space (bytes): 25070211072
Usable space (bytes): 25070211072

File system root: D:\
Total space (bytes): 194241359872
Free space (bytes): 145202843648
Usable space (bytes): 145202843648

File system root: E:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: F:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: Z:\
Total space (bytes): 249995624448
Free space (bytes): 30838194176
Usable space (bytes): 30838194176

Stack trace:
org.lateralgm.file.GmFormatException: java.io.FileNotFoundException: Compilers\Windows\gcc.ey (El sistema no puede encontrar la ruta especificada)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.util.Scanner.<init>(Scanner.java:680)
	at java.util.Scanner.<init>(Scanner.java:674)
	at org.enigma.file.YamlParser.parse(YamlParser.java:189)
	at org.enigma.EnigmaRunner.make(EnigmaRunner.java:277)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:173)

**Comment by RobertBColton** [comment]
@lcnvdl Hello, thank you for reporting this issue. It is however related to the ENIGMA plugin system it can not find compiler information from ENIGMA. Please post the issue on the ENIGMA plugin tracker.
https://github.com/enigma-dev/lgmplugin

Also, please indicate what you were doing at the time of the crash. If this is related to compiling a specific project and an empty game with no room does compile and run, then please include the project that failed to build. Otherwise we will help you discern what is wrong with your ENIGMA installation over on the correct tracker.
