### ISSUE TITLE
new issue ?

### ISSUE THREAD

**Issue by paulkokos** [IsmAvatar/LateralGM#219]
Operating System: Windows 7
Version: 6.1
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.8.0_45

Available processors (cores): 4
Free memory (bytes): 205482528
Maximum memory (bytes): 932184064
Total memory available to JVM (bytes): 257425408

File system root: A:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: C:\
Total space (bytes): 161679929344
Free space (bytes): 30013779968
Usable space (bytes): 30013779968

File system root: D:\
Total space (bytes): 536979144704
Free space (bytes): 187956035584
Usable space (bytes): 187956035584

File system root: E:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: F:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: G:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: H:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: I:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: L:\
Total space (bytes): 678842368
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:

java.lang.UnsatisfiedLinkError: Unable to load library 'compileEGMf': Native library (win32-x86-64/compileEGMf.dll) not found in resource path ([file:/C:/Users/paulkokos/Downloads/ENIGMA/enigma-dev/plugins/enigma.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at org.enigma.EnigmaRunner.attemptLib(EnigmaRunner.java:247)
	at org.enigma.EnigmaRunner.access$1(EnigmaRunner.java:240)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:178)

**Comment by JoshDreamland** [comment]
More than likely, your ENIGMA DLL was built using a 32-bit MinGW, while you are using a 64-bit JVM. Please replace your MinGW with the 64-bit installation, or run using a 32-bit JVM.

**Comment by RobertBColton** [comment]
@paulkokos Please follow the advice, he's correct that ENIGMA does not support work with 64 bit Java installations. If you would like to use LateralGM without ENIGMA you may continue to do so using a 64 bit Java, but if you intend to compile games and wish to use ENIGMA you will need to use a 32 bit Java until ENIGMA adds 64 bit support.
http://enigma-dev.org/docs/Wiki/Troubleshoot#Why_am_I_getting_an_error_about_compileEGMf.3F
This issue is unrelated to LateralGM, please post the issue on the ENIGMA plugin tracker if you are unable to resolve the issue.
https://github.com/enigma-dev/lgmplugin
