### ISSUE TITLE
Start pop-up error

### ISSUE THREAD

**Issue by deciia** [IsmAvatar/LateralGM#220]
Operating System: Windows 8.1
Version: 6.3
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.8.0_25

Available processors (cores): 4
Free memory (bytes): 193780592
Maximum memory (bytes): 932184064
Total memory available to JVM (bytes): 257425408

File system root: C:\
Total space (bytes): 106860376064
Free space (bytes): 39343292416
Usable space (bytes): 39343292416

File system root: D:\
Total space (bytes): 868850069504
Free space (bytes): 418598879232
Usable space (bytes): 418598879232

File system root: E:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:

java.lang.UnsatisfiedLinkError: Unable to load library 'compileEGMf': Native library (win32-x86-64/compileEGMf.dll) not found in resource path ([file:/D:/develop/ENIGMA/enigma-dev/plugins/enigma.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at org.enigma.EnigmaRunner.attemptLib(EnigmaRunner.java:247)
	at org.enigma.EnigmaRunner.access$1(EnigmaRunner.java:240)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:178)

**Comment by JoshDreamland** [comment]
More than likely, your ENIGMA DLL was built using a 32-bit MinGW, while you are using a 64-bit JVM. Please replace your MinGW with the 64-bit installation, or run using a 32-bit JVM.

**Comment by RobertBColton** [comment]
@deciia This issue is related to the ENIGMA plugin, not to LateralGM, please post the issue there.
https://github.com/enigma-dev/lgmplugin

If you check ENIGMA's troubleshooting page, it currently does not support a 64 bit Java installation but has steps that you can follow to resolve this issue.
http://enigma-dev.org/docs/Wiki/Troubleshoot#Why_am_I_getting_an_error_about_compileEGMf.3F

If you do not need to compile games you may continue to use lateralgm.jar without ENIGMA in the 64bit Java installation, if you intend to use ENIGMA you will need to install the 32bit JVM until ENIGMA adds support for 64bit.
