### ISSUE TITLE
Feature: Add script name display in editor

### ISSUE THREAD

**Issue by Kayomn** [IsmAvatar/LateralGM#233]
So in Enigma's counterpart, Game Maker, you are able to see the name of your scripts within the object you're working on. Coming from past experience from Game Maker it seems really inconvenient for all of your scripts to be named the stock value.

Surely it couldn't be that hard to make the name of the entry in the list change to the first line of the file's "///...".

Thanks in advance.

**Comment by JoshDreamland** [comment]
I believe it would be wise to support all four formal comment notations. At very least, I'd support these two:
```C++
/// Formal comment naming the file
```
```C++
//! Formal comment naming the file
```
It's probably wise to support these two, as well, on a first-line basis:
```C++
/**
 * Name of the file
 * Possibly other junk here
 */
```
```C++
/*!
 * Name of the file
 * Possibly other junk here
 */
```
My main objection to this is that formal comments are so called because the contents of them follow a specific grammar. The most popular of these is Doxygen. In a perfect world, the above would be acceptable, but could be overridden by `@brief` / `\brief`, or maybe `@file` / `\file`.

By specification of Doxygen, the brief of a function is the first sentence of its description (stopping at the period), unless the `\brief` tag is present, in which case, it's the block of text following that until the first *pair* of newlines. So, consider this snippet:
```C++
/*!
 * Does some stuff. In an inefficient and horrific fashion.
 */
void foo();

/**
 * @brief Does some stuff. In an inefficient
 * and horrific fashion.
 *
 * Also makes sandwiches.
 */
void bar();
```

So according to Doxygen, the brief for `foo()` is "Does some stuff." The brief for `bar()` is "Does some stuff. In an inefficient and horrific fashion."

That said, there's really no precedent for documenting the contents of a script. Doxygen was designed for languages with larger compilation units, so `@file` is used to document an entire file. But we're not dealing with files, here. Since `@brief` cannot apply to functions, as nested functions aren't supported in GM/ENIGMA, it might make sense to use it. But the situation is a bit weird, looking through the lens of Doxygen's intended use.

All that said, I don't know if, for instance, a JavaDoc parser would be available cheaply to LGM, but if it were, this could be a quick way of supporting Doxygen tags. For all I know, a Doxygen parser is really cheap (though I highly doubt it). Otherwise, given the lack of precedent for this sort of thing, the first-line approach sounds reasonable to me. I'd support all four of those comment specs.

**Comment by RobertBColton** [comment]
While I would also prefer something more elaborate as @JoshDreamland describes, I've now noticed it was in GM8.1 by Overmars. I think for now simply '///' will suffice.

**Comment by rpjohnst** [comment]
There is precedent for doc comments being inside a function- Doxygen supports this (see references to "in body" descriptions here: http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html#cppblock), Python docstrings always go inside their function, etc.

However, I think supporting anything like Doxygen in LateralGM would be like using a nuke to kill a fly. All we need is to read two or three comment styles from the first line(s) of a script to extract a name, and honestly all we really need is the one triple-slash format GM:S uses.

**Comment by JoshDreamland** [comment]
I prefer to think of it as nuking the fly planet. But anyway, agreed—I specifically said this isn't worth the effort (or additional bytes) if a JavaDoc parser is not readily available as part of the Java runtime. This would not surprise me, given that the HTML renderer for it *is*. So my question is, is `com.sun.javadoc.*` available by default? Or is something similar from the modern era? If so, I think it makes more sense for a project operating out of a nuke factory to bomb a fly than to order a flyswatter, even given Prime shipping.

**Comment by RobertBColton** [comment]
@rpjohnst and @JoshDreamland I am now really just asking about how to handle the white space around the comment as described in the table above.

**Comment by JoshDreamland** [comment]
Your proposal is fine with me.

**Comment by RobertBColton** [comment]
Alright I've finished my first attempt at this in https://github.com/RobertBColton/LateralGM/commit/2a7f19e20e6954aa6b48cf0537477cdba3b22965 and then revised it in https://github.com/RobertBColton/LateralGM/commit/d95d9e60724836d3b538c2a1cc6447a182f7b7f9

**Comment by RobertBColton** [comment]
Feature implemented in master, will be available in the next release.
