### ISSUE TITLE
Completion needs to deselect before selecting

### ISSUE THREAD

**Issue by IsmAvatar** [IsmAvatar/LateralGM#25]
Original submission:
"in your code completion code, call deselect() after you adjust the caret position"
Assuming this means the old selection is not cleared properly.

**Comment by RobertBColton** [comment]
I keep trying to reproduce the issue this user could have had, but I just keep failing to find anything other than the above which I don't think is the original issue. One possibility is the user may have mistaken the completion window selecting/highlighting the first argument for you to easily replace as a bug and not realized this is an intentional feature.
