### ISSUE TITLE
Not all properties saved and loaded

### ISSUE THREAD

**Issue by faissaloo** [IsmAvatar/LateralGM#255]
When saving a file the 'Use New Audio Engine' checkbox in game settings does not get saved, even if it was ticked by Game Maker. The checkbox is also not present in game settings so I can not change it.

**Comment by RobertBColton** [comment]
Sadly this is a known issue that is hard to address. The problem is that we only load properties from the that we are aware of. So if YoYoGames updates the GMX format and adds new global game settings as an example LGM will have to immediately add all of those settings to at least be loaded and saved in a new release. This is clearly not feasible as we already haven't gotten around to adding all the cross-platform settings. However, I do believe they began adding version numbers to GMX recently, so the best solution is probably to just complain about this and inform the user when they load a GMX version LGM does not support.

**Comment by RobertBColton** [comment]
I feel obligated to mention this is still an ongoing issue. For example, although #433 is an improvement to our destructive GMX writing, we still destroy the config export information for each included data file. Again, it's still better than our previous total destruction of included files, but still not ideal.

**Comment by RobertBColton** [comment]
Small update to this, the original missing setting posted here has been added in #547 and is included in the 1.8.222 release available now. Obviously, there's still missing settings in some places yet.

What's missing still for GMSv1.4 basically boils down to:
* Per-platform graphics settings
* Steam/Ads/Other tabs
* Texture Groups
* Audio Groups
* User extensions resource (although we aren't currently destroying this, we don't touch them if they exist)
