### ISSUE TITLE
Includes and Extensions are not working

### ISSUE THREAD

**Issue by LiarOnce** [IsmAvatar/LateralGM#299]
I click on the install button in the Extensions folder, but it does not pop up any window.
So I can't install any extensions.
And the includes folder,I can't use any file after I import a file.

**Comment by RobertBColton** [comment]
Hi LiarOnce! Thank you for reporting this but we are actually already aware of the issue, so I have to close this. This ticket is a duplicate of #61, when someone has time the Extensions and Includes need finished. It is something I am considering to do for the next release since we've finished cleaning up the source code quite a bit.
