### ISSUE TITLE
Unknown function or script `draw_set_colour'

### ISSUE THREAD

**Issue by aceri** [IsmAvatar/LateralGM#322]
When compiling i get 
Line 15, position 24 (absolute 430): Unknown function or script `draw_set_colour'

When changing it to draw_set_color everything is fine.

I think Gamemaker has both version names, the english and american ones (?)
Many english secondary language speakers like me  i guess never ever knowing which is the right one :-)
I wonder if it happens the same with gray and grey, center and centre.

Just that. Thanks for your awesome support and software that has me literally with my mouth open of how incredible it is. Just starting playing with it an hour ago.

And sorry if this small detail has not enough entity for the issue.

Astonished regards :-)

**Comment by faissaloo** [comment]
This is because at least for now, the ENIGMA devs have decided to stick to only American English in order to prevent things becoming messy.  
We had a conversation about it here
https://github.com/enigma-dev/enigma-dev/issues/950  
Btw this is the LateralGM bugtracker please post in the enigma-dev one next time.

**Comment by RobertBColton** [comment]
Hrm... well one thing is that LGM does have a list of keywords and functions that it uses for syntax highlighting. This is so LGM can do syntax highlighting when not hooked up to ENIGMA. When it is hooked up to ENIGMA, ENIGMA will scan the major systems and look for overloads and additional functions to syntax highlight.
https://github.com/JoshDreamland/JoshEdit/blob/master/org/lateralgm/joshedit/lexers/gmlfunctions.txt

I wonder if we should add the British spelling versions in there anyway though, since LGM kind of technically supports GMS. However, if we did that then people might get confused when it is hooked up to ENIGMA and think ENIGMA supports the function then since it's syntax highlighted.

For now stick to draw_set_color and the Americanized function names either way though. Also I just want to say that I hate YYG's for making this an issue, I would have just left it Americanized. This is not a problem that anybody is really trying to solve, most foreigners just get used to American English when it comes to programming.

**Comment by SuperRiderTH** [comment]
For what it is worth, Studio 2 actually has the option to _DISABLE_ US spelling now.
![image](https://cloud.githubusercontent.com/assets/5368844/20460258/a2d24ddc-aeab-11e6-9a66-b2bb8e24f057.png)

**Comment by JoshDreamland** [comment]
ENIGMA supplies LateralGM with a custom keyword list. Since LGM seeks compatibility with GM's IDE, it should have these alternate spellings in its default list of keywords (which is a mirror of the comparatively more stable list of functions, which rolls around with each new GM release).
