### ISSUE TITLE
On saving, LGM crashed and corrupted my save file.

### ISSUE THREAD

**Issue by IgazHarcos** [IsmAvatar/LateralGM#323]
Operating System: Windows 10
Version: 10.0
Architecture: x86

Java Name: Java HotSpot(TM) Client VM
Java Vendor: Oracle Corporation
Version: 1.8.0_111

Available processors (cores): 4
Free memory (bytes): 212056856
Maximum memory (bytes): 1013645312
Total memory available to JVM (bytes): 259588096

File system root: C:\
Total space (bytes): 284761780224
Free space (bytes): 82021048320
Usable space (bytes): 82021048320

File system root: D:\
Total space (bytes): 215236997120
Free space (bytes): 64068956160
Usable space (bytes): 64068956160

File system root: E:\
Total space (bytes): 7754215424
Free space (bytes): 5845155840
Usable space (bytes): 5845155840

File system root: F:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:
org.lateralgm.file.GmFormatException: org.xml.sax.SAXParseException: Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:221)
	at org.lateralgm.file.GMXFileReader.readProjectFile(GMXFileReader.java:200)
	at org.lateralgm.main.FileChooser$ProjectReader.read(FileChooser.java:385)
	at org.lateralgm.main.FileChooser$1.run(FileChooser.java:588)
	at java.lang.Thread.run(Unknown Source)

**Comment by faissaloo** [comment]
This happens sometimes, usually it's just the main .project.gmx that's been corrupted, if you have backups enabled use those otherwise you can copy the .project.gmx file from another project and transplant it to the .gmx folder you can open it the .project.gmx file and modify it to fit your project structure, usually nothing else gets damaged.

**Comment by RobertBColton** [comment]
Thanks for reporting this! I'm sorry that this happened without better notice ☹️. As a result of this issue I have now taken steps to mitigate project corruption, including fixing some bugs in the backup mechanism and supporting GMX backups. If you download the latest LGM 1.8.133 you will now see that LGM's default backups limit has been increased to 5 copies, you can now directly open GMK *.gb1-*.gb9 backup files, and GMX will now backup your entire project's directory instead of just the main manifest file. GMX is backed up in the same way as GMK was in classic GameMaker, that is to say, LGM does not use a dedicated backups directory in user Documents as GameMaker does and will backup your project in the same directory as it's being saved plus replace *.gmx with the *.gb1 extension in the directory name.

* eb38c00b5f0b3fbe8e53460e9907b7024dc67992 fixes and increases the backup limit and asks the user for overwrite confirmation in the case of error.
* c257080404a69df0135754dae13508e6a0e14e08 provides GMX backup support.
* 880ba286deba3a110dc69d2b6b674f25a9293e6a allows direct opening of *.gb1-*.gb9 GM backup files.

In a future release we will (#178) make the Preferences frame actually have working settings for the backups too.

While I understand that this issue you faced may be frustrating, I hope that you will find these changes helpful and continue to report issues to us so that we may address them. I will now close this issue as resolved, and if you have any more problems please let us know!

**Comment by RobertBColton** [comment]
Just want to add that with 39b37b4adecf603fe9ba3d55efb209fdcb1ce1bf the latest 1.8.134 now has working preferences for the backups and an autosave that can be enabled. I hope that these changes also will help mitigate issues like this from occurring in the future, or at least not make them as bad.
