### ISSUE TITLE
Project file is sometimes corrupted for no reason.

### ISSUE THREAD

**Issue by KelvinShadewing** [IsmAvatar/LateralGM#327]
Sometimes when I load a project, I'll get a long error message saying the file is corrupted, and one of three things will happen: everything is there and it seems to be a false alarm, nothing is there at all, or the asset tree is there but no assets are in it. I replaced my project with a backup, and while it looks like it loaded successfully, it still gives me the error each time I open it, and I'm afraid to keep working on it because I'm afraid it'll delete everything again.

Here's the error message I got:

> ```Operating System: Linux
> Version: 4.8.0-53-generic
> Architecture: amd64
> 
> Java Name: OpenJDK 64-Bit Server VM
> Java Vendor: Oracle Corporation
> Version: 1.8.0_131
> 
> Available processors (cores): 4
> Free memory (bytes): 103664352
> Maximum memory (bytes): 1834483712
> Total memory available to JVM (bytes): 200278016
> 
> File system root: /
> Total space (bytes): 483790184448
> Free space (bytes): 330143682560
> Usable space (bytes): 305544982528
> 
> Stack trace:
> java.lang.NullPointerException
> 	at org.enigma.file.EFileReader.readResource(EFileReader.java:665)
> 	at org.enigma.file.EFileReader.processEntries(EFileReader.java:643)
> 	at org.enigma.file.EFileReader.readNodeChildren(EFileReader.java:621)
> 	at org.enigma.file.EFileReader.readEgmFile(EFileReader.java:559)
> 	at org.enigma.file.EFileReader.readEgmFile(EFileReader.java:537)
> 	at org.enigma.file.EgmIO.read(EgmIO.java:56)
> 	at org.lateralgm.main.FileChooser$1.run(FileChooser.java:588)
> 	at java.lang.Thread.run(Thread.java:748)

It happens whether I'm saving as GMK or EGM, and saving as GMX gives me an empty project.

**Comment by Hughtech** [comment]
ENIGMA only works with 32bit JAVA, so make sure that you have installed one. I can either be version & or 8, so download the appropriate one and try again.

**Comment by KelvinShadewing** [comment]
I installed the 32-bit version, but it's still trying to use 64-bit OpenJDK. How do I change that?

**Comment by Hughtech** [comment]
In that case you will have to point it to the 32bit version. Follow this method done here:
https://youtu.be/xatsn3LNLFk

**Comment by KelvinShadewing** [comment]
Do you have any info how how to do this in Linux? Preferably a non-video, as I'm on a very poor connection.

**Comment by JoshDreamland** [comment]
The 32-bit Java thing is a Windows problem, as far as I know. Robert has been working on the file corruption issue. But I thought corruption only affected GMX; you're getting it with both EGM and GMK? How big is your game?

**Comment by Hughtech** [comment]
Instead of having two versions installed and switching from one to the other, delete all versions of java first then re-install the 32-bit version and work with that alone.
To do this in LINUX, first we must be root. You can either use '**su**' and the type in each lines of commands normally or use **sudo** in front of each line of commands, I will be using **sudo**

Open up a "terminal" window and type these commands pressing your Enter key after each.
![remove java commands](https://user-images.githubusercontent.com/19632613/34937440-43085cd2-f9bb-11e7-897b-121aebc49fcc.png)

This should be enough. Now comes the tricky part. To install the 32-bit version we must add support for it on a 64-bit system. 
**sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install openjdk-7-jre:i386**

Get back to me when you've done this.

**Comment by Hughtech** [comment]
Instead of having two versions installed and switching from one to the other, delete all versions of java first then re-install the 32-bit version and work with that alone.
To do this in LINUX, first we must be root. You can either use '**su**' and the type in each lines of commands normally or use **sudo** in front of each line of commands, I will be using **sudo**

Open up a "terminal" window and type these commands pressing your Enter key after each.
![remove java commands](https://user-images.githubusercontent.com/19632613/34937440-43085cd2-f9bb-11e7-897b-121aebc49fcc.png)

This should be enough. Now comes the tricky part. To install the 32-bit version we must add support for it on a 64-bit system. 
**sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install openjdk-7-jre:i386**

Get back to me when you've done this.

**Comment by KelvinShadewing** [comment]
Error: openjdk-7-jre:i386 has no installation candidate

**Comment by KelvinShadewing** [comment]
Installed, got another error:


Operating System: Linux
Version: 4.8.0-53-generic
Architecture: i386

Java Name: OpenJDK Server VM
Java Vendor: Oracle Corporation
Version: 1.7.0_95

Available processors (cores): 4
Free memory (bytes): 78111280
Maximum memory (bytes): 954466304
Total memory available to JVM (bytes): 119799808

File system root: /
Total space (bytes): 483790184448
Free space (bytes): 223119261696
Usable space (bytes): 198520561664

Stack trace:
java.lang.NullPointerException
	at org.enigma.file.EFileReader.readResource(EFileReader.java:665)
	at org.enigma.file.EFileReader.processEntries(EFileReader.java:643)
	at org.enigma.file.EFileReader.readNodeChildren(EFileReader.java:621)
	at org.enigma.file.EFileReader.readEgmFile(EFileReader.java:559)
	at org.enigma.file.EFileReader.readEgmFile(EFileReader.java:537)
	at org.enigma.file.EgmIO.read(EgmIO.java:56)
	at org.lateralgm.main.FileChooser$1.run(FileChooser.java:588)
	at java.lang.Thread.run(Thread.java:745)

Also, now some folders instead of showing the name like Sprites and Backgrounds, it shows a piece of HTML code, and the folders don't highlight properly when selected. Sometimes they don't change and sometimes several will be highlighted at once.

**Comment by Hughtech** [comment]
Sorry about the long response. I'm been really, really busy with some part-time work, building my office and dealing with other matters. So I didn't get much time to be online.

Wow! Seems to me like you have a bigger than just the java one alone.
What type of LINUX are you using? Did you install ENIGMA without any errors when you tried to?
Consider these questions and if you did get some errors, then maybe you need to try re-installing it again.

**Comment by RobertBColton** [comment]
Switching to a 32bit Java installation is not going to solve these problems. The 32bit problem has to do with running ENIGMA on Windows where the Portable ZIP comes with a 32bit MinGW.  You must run LateralGM with a Java that is of the same architecture compileEGMf.dll was compiled with. In other words, this problem has nothing to do with Linux, your 64bit installation was fine.

On a related note, OpenJDK is demonstratively buggier than OracleJDK. You may notice freezing progress bars and other dialogs using the OpenJDK to run LateralGM at times. This may make it appear as though something is going wrong during save/load of the project. So it does sometimes help to switch to Oracle's proprietary JDK to use LateralGM.

Now the real reason for these corruptions is due to the way LateralGM handles various project formats, and mostly my fault. Because LGM must support 3 different formats (EGM, GMX, and GMK), its strategy is to load everything from all of them at all times. You can see this with the sound frame where it loads the old options for effects as well as the new ones added for GMS. This is so that project saving and loading is lossless. One could argue that this was perhaps not the best strategy, but LGM's primary goal was to be a GameMaker IDE, not an ENIGMA one.

So the reason for some of these problems is me moving different things around and not making sure everything saves correctly between them. One of these issues is related to multiple configurations, which I believe EGM still only saves one of because I didn't get the chance to ask Josh if he wanted to support that. Solving this problem just takes a good sitting down and looking at all of the readers/writers to make sure they are saving things correctly. I lost interest in doing this in sight of fixing other ENIGMA related issues, but anyone is welcome to send a PR here or finish mine #334.

**Comment by Hughtech** [comment]
I stand corrected RobertBColton. So the best bet for him then is to re-install ENIGMA then.

**Comment by JoshDreamland** [comment]
Better bet is to use Oracle's JVM to mitigate Java bugs, and if the problems persist, send us a test case. Again, is this a particularly big game? How frequently are these problems occurring?

**Comment by Hughtech** [comment]
He is using the LINUX installation on a 64bit machine. Linux always want to install the OPENJDK so how can one use ORACLE's JVM?

**Comment by RobertBColton** [comment]
See #337 that Josh just reported, it was another OpenJDK bug. OpenJDK is so buggy to the point of not even usable, at least with regards to Swing.
https://askubuntu.com/a/751598

**Comment by Hughtech** [comment]
I'm trying to do as you suggested but unfortunately I've got these errors.

You are about to add the following PPA to your system:
 Oracle Java (JDK) Installer (automatically downloads and installs Oracle JDK7 / JDK8 / JDK9). There are no actual Java files in this PPA.

Important -> Why Oracle Java 7 And 6 Installers No Longer Work: http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html

Ubuntu 16.10 Yakkety Yak is no longer supported by Canonical (and thus, Launchpad and this PPA). The PPA supports Ubuntu 17.10, 17.04, 16.04, 14.04 and 12.04.

More info (and Ubuntu installation instructions):
- for Oracle Java 7: http://www.webupd8.org/2012/01/install-oracle-java-jdk-7-in-ubuntu-via.html
- for Oracle Java 8: http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

Debian installation instructions:
- Oracle Java 7: http://www.webupd8.org/2012/06/how-to-install-oracle-java-7-in-debian.html
- Oracle Java 8: http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html

Oracle Java 9 (for both Ubuntu and Debian): http://www.webupd8.org/2015/02/install-oracle-java-9-in-ubuntu-linux.html

Oracle JDK 9 is now considered stable. **There are currently only 64bit builds (no other builds are available for download**: http://www.oracle.com/technetwork/java/javase/downloads/index.html )
 More info: https://launchpad.net/~webupd8team/+archive/ubuntu/java
Press [ENTER] to continue or ctrl-c to cancel adding it

WARNING:root:could not open file '/etc/apt/sources.list'

WARNING:root:could not open file '/etc/apt/sources.list'

Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 167, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for MX/Metamorphosis

**Comment by Hughtech** [comment]
ok at first i had those errors Then I followed the Instructions on How to Install Oracle Java 8 in Debian and it successfully installed.
By following your instructions RoertBColton, I hope KelvinShadewing be successful also. thanks a lot for your input!

**Comment by KelvinShadewing** [comment]
> LateralGM Version: 1.8.10
> 
> Operating System: Linux
> Version: 4.8.0-53-generic
> Architecture: amd64
> 
> Java Name: Java HotSpot(TM) 64-Bit Server VM
> Java Vendor: Oracle Corporation
> Version: 1.8.0_161
> 
> Available processors (cores): 4
> Free memory (bytes): 68099360
> Maximum memory (bytes): 1834483712
> Total memory available to JVM (bytes): 159383552
> 
> File system root: /
> Total space (bytes): 483790184448
> Free space (bytes): 267736768512
> Usable space (bytes): 243138068480
> 
> Stack trace:
> java.lang.NullPointerException
> 	at org.enigma.file.EFileReader.readResource(EFileReader.java:665)
> 	at org.enigma.file.EFileReader.processEntries(EFileReader.java:643)
> 	at org.enigma.file.EFileReader.readNodeChildren(EFileReader.java:621)
> 	at org.enigma.file.EFileReader.readEgmFile(EFileReader.java:559)
> 	at org.enigma.file.EFileReader.readEgmFile(EFileReader.java:537)
> 	at org.enigma.file.EgmIO.read(EgmIO.java:56)
> 	at org.lateralgm.main.FileChooser$1.run(FileChooser.java:588)
> 	at java.lang.Thread.run(Thread.java:748)

Still not working. Using Oracle Java 8.

**Comment by RobertBColton** [comment]
Small update, going to close this for several reasons. If you would like to still recover that EGM project, I can convert it to another GMX or GMK format for you if you attach it in a reply. Also, for your information, it's just a zip file and you should be able to change its extension and extract it if you chose to do it yourself.

1) Old EGM has now been disabled due to its instability problems. All EGM related issues have been combined together into a parent ticket explaining the issues on the ENIGMA for LGM plugin tracker. You can no longer select to save or open (open didn't even work) EGM anymore from the file choosers.
https://github.com/enigma-dev/lgmplugin/issues/82
2) Old EGM will be replaced by the new EGM from enigma-dev's CI tested libEGM library. It's not binary, it's tested, and it will be much more stable.
3) A number of commits (12ea9ca93f7bc5e7ef63f1a35c1427b1744be543, c257080404a69df0135754dae13508e6a0e14e08, 39b37b4adecf603fe9ba3d55efb209fdcb1ce1bf) have been pushed to fix GMX backups and provide working backup and autosave preferences.
4) Initial and project loading thread safety (010d1c1fc314703f0929b48331f14da44c270d98 & e20a439fcf54d5772f0d38231334859618bb4baa) has been pushed to improve the LGMs stability and mitigate OpenJDK issues.

All of this is in addition to a load of other improvements to project loading since this issue was originally filed in 2017. If you continue to have more issues, I do encourage you to try again the latest release and to please report back if you encounter other issues. I say this because this is the only way to know for sure whether the thread safety improvements have actually improved the OpenJDK situation with LGM. I hope that these changes do help and that you will find them useful. Thanks, and again, we look forward to helping you solve any further issues!
