### ISSUE TITLE
Sprite Editor: Changing Animation Speed has no effect

### ISSUE THREAD

**Issue by Wend1go** [IsmAvatar/LateralGM#330]
Changing the "Animation Speed" in the sprite editor has no effect.
If you set a different Speed and save the sprite it shows the default value of "30" again if you reopen it.

**Comment by JoshDreamland** [comment]
The animation speed is just for preview purposes (so you know what the sprite would look like running at a particular framerate). If you want that speed to be used in Game Maker/ENIGMA, you'll need to set the `image_speed` local of the object using that sprite.

**Comment by Wend1go** [comment]
Ah I see. Thanks for clarification.
Closing the issue.

**Comment by RobertBColton** [comment]
The latest iteration of the editor has that in the top "preview" toolbar with only other non serialized preview settings. I hope that it makes it clearer to people but we could also revisit this. It may be worth it to even change the name from "Animation Speed" to "Preview Speed" since "Preview" is actually the terminology that GM itself used.
![Sprite Editor Revamped](https://user-images.githubusercontent.com/3212801/90841977-1d6d7400-e32c-11ea-904c-5608d0c8e5e4.png)
