### ISSUE TITLE
Corrupt or missing Lateralgm from Repository

### ISSUE THREAD

**Issue by Hughtech** [IsmAvatar/LateralGM#335]
I tried re-installing ENIGMA from source and after when I tried to run Lateralgm, it reported the file was corrupted. I tried to get a fresh copy manually from Github but it is nowhere to be found.

**Comment by RobertBColton** [comment]
I don't exactly understand what happened. Can you please paste any relevant logs or errors you received?

A jar file, which is used to execute Java programs, of LateralGM can be obtained from the releases page:
https://github.com/IsmAvatar/LateralGM/releases

**Comment by Hughtech** [comment]
To explain fully:
I started to re-install ENIGMA on one of my LINUX machines when I encountered various errors. Not a really big issue since I was testing an Update to my previous OS. however I was concerned when I received several messages stating that the IDE was corrupt when I tried to run LateralGM.

![screenshot from 2018-01-06 15-47-10](https://user-images.githubusercontent.com/19632613/34654306-58335e40-f3d0-11e7-8499-1d8468eda154.png)


This happened at every fresh install using 3 separate LINUX OS; Ubuntu, MINT and MX LINUX 17. I had to re-install my old MX LINUX 16.1 and copy LateralGM from a previous backup in order to get it up and running. 
I had tried to use Version 1.8.10 before but JAVA crashed, so I then returned back to version 1.8.7. Now you have released an even newer one, I will test it out.

**Comment by RobertBColton** [comment]
Thanks, yeah that helps. This is really really really strange as I've never seen anybody have the jar file of LateralGM corrupt before. This is the first time this has ever been reported to any of us. When you say you tried to update/reinstall ENIGMA, did you happen to rerun install.py? This will download a new LateralGM jar by comparing the MD5 hash of the file to the ones we host in this other repo:
https://github.com/enigma-dev/ExtraPackages/blob/master/Packages.md5

I am thinking hypothetically that perhaps there was an issue in that download script that caused the file to corrupt, but I still don't know because I've not heard of this and I did not write that script either. Definitely give the newer version a try and let me know if there are any errors running LGM, because I just fixed some exceptions related to starting LGM in Java 9.

**Comment by Hughtech** [comment]
I too have never seen or heard of this before which prompted me to test it on other distros. Each had the same effect which gave me cause of concern. I will also mention it on the ENIGMA tracker as well. I've also open another issue with the newer version of LGM as well.

**Comment by RobertBColton** [comment]
Sounds good, I am going to close this here.
