### ISSUE TITLE
Suggestion: add option to automatically reload changed resources

### ISSUE THREAD

**Issue by 9Morello** [IsmAvatar/LateralGM#341]
If I'm using an external editor with LateralGM and make changes to my project, I need to close it and load it again for the changes to appear.

This completely breaks workflow with [GMEdit](https://github.com/GameMakerDiscord/GMEdit), a fantastic code editor for Game Maker projects. So, I suggest an option similar to Game Maker: Studio's **"Always reload changed files"** feature.

**Comment by RobertBColton** [comment]
Ok, so I was going to close this as impossible with the LGM architecture, but it would actually be possible to achieve this. However, I think it would be a complete nightmare to do because of the threading and concurrency issues with LGM.

So, because LGM supports GMK, it loads the entire project up front. This behavior was copied for the GMX reader when I wrote it. This allows lossless conversion of GM projects using LGM, which is LGM's primary goal being a GM IDE, not an ENIGMA IDE. So, the way to do this with LGM would probably be a complete rewrite of the GMX reader, which I started with #334. However, you would need to go farther than that pull request and extend the GMX reader to not load the metadata or use a regular ResNode for the tree. It should make a custom FileNode that extends ResNode and will lazy load the resource as it is requested.

Using this strategy LGM would then load GMK files all at once at start and it would lazy load GMX files. But then saving the projects would get extremely more complicated as would loading one format and saving as another. That said, I have no plans to work on this, but the suggestion can remain.

**Comment by RobertBColton** [comment]
I did some more thinking on this, and while LGM is mostly in maintenance mode, this could be done very easily. The problem lies in the fact of whether you would want this for GMK too. GMK being a binary blob as people know, isn't set up for streaming small individual resources. Obviously we could monitor the root GMK and GMX and ask the user to reload the entire project.

However, reloading the entire problem would do some undesirable things like reset the project tree expanded state etc. It would also cause the editors to close and everything. As a first implementation, to have this for GMK too, we could possibly hack around that. Regardless, I think what people are really after is reloading individual assets, like GMX, because it's not only quicker than an entire project reload, it doesn't have the other issues. A single class, which monitors the project, could notify the user of a change to any file in the project directory. Then it could simply map the changed file to a tree node in the tree, read in the file by switching on the resource type, and overwriting all the properties in the property map of the tree node's resource.

**Comment by 9Morello** [comment]
Thanks for coming back to this. What would be the use case for live reloading GMK projects?
This is interesting for .gmx/.yyp because it allows you to use external editors more seamlessly, but I've never heard of people doing that with older Game Maker projects.

**Comment by RobertBColton** [comment]
Allow me to clarify, I meant to imply that GMK would be pretty useless, but was also speaking from an implementation perspective. Although in #495 I declined to work on GMS2 support, a generalized asset reloader could apply to any and all formats including GMK/GMX/YYP/EGM or whatever. Excluding GMK in that case would have to be intentional.
