### ISSUE TITLE
Code Windows Stay On Top

### ISSUE THREAD

**Issue by mikeypro83** [IsmAvatar/LateralGM#381]
In the IDE, the code editor windows stay on top of all other windows even when you select a window behind it.
![behaviorimtalkingabout](https://user-images.githubusercontent.com/41976933/46920987-1ac4c980-cfb3-11e8-9aef-dd1be41b5064.png)

**Comment by RobertBColton** [comment]
Hey mikey! Only the action ones will stay on top because all of the action windows are parented to the object editor. If you use scripts instead it should not be a problem. Honestly, that could be made into a preference, so I'll leave this ticket open for you. However, I am focusing my efforts on RGM. Hope I helped!

**Comment by mikeypro83** [comment]
Closing old issue.
