### ISSUE TITLE
GMS2 Support?

### ISSUE THREAD

**Issue by softwareantics** [IsmAvatar/LateralGM#495]
Hi, LateralGM looks like it's exactly what I'm looking for! Just wondering if there will be support for GMS2 projects? If so, I'd love to contribute so we can get the ball rolling a little faster :)

**Comment by JoshDreamland** [comment]
To be honest, we're short-handed, and the developers who maintain this project have shifted their focus away from Java and onto Qt-C++ after recurring problems with OpenJDK and Swing. The project is basically in maintenance mode, which is to say, Robert occasionally gets froggy and decides to fix some breakage with the codebase on new JVMs. The GMX reader we have in LGM is buggy, as I understand; I don't see anyone adding support for another importer.

That said, we haven't abandoned this project. You might find help implementing this on the ENIGMA or Dejavu Discord servers.

**Comment by RobertBColton** [comment]
Hey, thanks for reaching out! 😃 
Let me start off bluntly and say that this probably isn't going to happen for a couple of reasons. LateralGM is really only in maintenance mode now and not actively developed. GMS2 is untenable considering the massive amount of re-engineering required to retrofit LGM to it. It's also impractical when LGM never even reached full GMSv1.4 compatibility (almost).

You really wouldn't even want to edit GMS2 projects in LGM anyway because of it being Java. I can tell you that enigma-dev's new libEGM does already support YYP, though I need to fix a few things there first because it's not CI tested like GMX is. This is not to say I wouldn't accept a pull request adding YYP reading to LGM for backporting games, but I probably will not accept a writer because it's unlikely that it would produce a full non-destructive serialization of GMS2 projects.
https://github.com/enigma-dev/RadialGM

I'm sorry if this isn't exactly what you wanted to hear, but we want to prioritize what's best for the community. If you do have any other ideas or feedback, please do come back, we love to hear from you!
