### ISSUE TITLE
Can't use Clang Anymore.

### ISSUE THREAD

**Issue by time-killer-games** [IsmAvatar/LateralGM#523]
g++ is now the hard coded compiler that LGM uses regardless of whether i select clang.

Which means you completely destroyed the ability to export to FreeBSD. Thanks Robert.

Pretty sure this was done for no reason.

**Comment by time-killer-games** [comment]
After further inspection the problem is not that it's using g++ that was based on assumption because an empty game segfaulted and it was a known issue that g++ did that but apparently now clang does it too. I'll see if I can fix this on my end, since it may have nothing to do with lgm after all.

**Comment by time-killer-games** [comment]
@RobertBColton @JoshDreamland @fundies

Hey guys, I found out the real problem. The version of libsndfile that came with my system update wasn't the right version and created conflicts with the version of alure ENIGMA uses. I'm not sure if there will ever be a case where this effects windows or linux, but just to play it safe, do you think I should add libsndfile1-dev (Ubuntu/Debian) and other platform equivalent packages to the installation wiki? You know, for the off chance someone has an incorrect version of that package installed?

**Comment by RobertBColton** [comment]
That seems like a fine idea for the Ubuntu/Linux troubleshotting FAQ, but I wouldn't go overboard with Windows because you don't know and it also uses pacman (which is Arch oriented) and so probably won't have that, but will instead have some other kind of a package issue. Also for the future, only LGM issues go here, if it was really the case the ENIGMA was selecting the wrong compiler it would go on enigma-dev repo or the lgmplugin because the compiler selection is actually done by ENIGMA. LGM repo is nothing more than a GM file editor.

**Comment by time-killer-games** [comment]
Sounds good. I'll add that to the wiki. Yeah, I realized this was probably related to the lgm plugin and not lgm itself, but thought of it after the fact, and I discovered what the real issue was by that time. I'll make sure in the future I do a better job about putting issues in the right place.

**Comment by RobertBColton** [comment]
It's not a big deal, I don't really care, it's not my repo, I think it's funny how everybody gets it wrong though.
