### ISSUE TITLE
JNA crashes LGM

### ISSUE THREAD

**Issue by hpgDesigns** [IsmAvatar/LateralGM#555]
### Describe the bug

When a clean install is performed, after doing a clean build of the make process, LGM crashes. you can refer to the entire error message here https://pastebin.com/Q4C3CdZF

### Steps To Reproduce

1. do a fresh install including downloading JNA from the main respository
2. Go to 'enigma-dev directory and run start LGM...'

### Expected behavior

LGM should run without issue.

### Exceptions & Error Messages

 you can check the error log here...... https://pastebin.com/Q4C3CdZF
 Using Manjaro KDE 21
 16Gb DDR4
 500GB NVME SSD

### Game Files & Screenshots

![Screenshot_20210731_024334](https://user-images.githubusercontent.com/75296992/127731368-ad0c5231-3070-4167-9196-9767e4a115e4.png)

### Additional context

 This happens not only on my Linux but on Windows setups as well. I have had to use a previous backup to solve this issue.

**Comment by RobertBColton** [comment]
Confirmed to be NOT an LGM bug. It's because the ENIGMA website was down while being repaired, so if you go look at `enigma-dev/plugins/shared/jna.jar` and open it in a text editor, you should see a 404 error code. What you need to do is go manually download a jna.jar from the official JNA repo. Thanks for reporting this!
