### ISSUE TITLE
Extensions and Includes parent ticket

### ISSUE THREAD

**Issue by IsmAvatar** [IsmAvatar/LateralGM#61]
Since we're getting a lot of tickets between both of these and it's highly related, I figured I'd make a parent ticket so we don't have to track separate tickets for them anymore.

Directly related:
- GEX reader/writer
- #5 Move Extensions from Tree to Game Settings 
- #45 Extensions and Included Files
- #57 Game Maker Studio Extensions Folder
- #60 Included Files Folder

Somewhat related:
- #56 Error Opening GM81 Project File [u524]

**Comment by RobertBColton** [comment]
Just want to mention that #434 resolves all of the issues with the included files. I came up with a solution that's forward and backward compatible with all GM versions, including GMSv1.4. I ultimately did decide to use a primary resource group, like GM5 and GMSv1.4, since that's easier to navigate using LGM's search features and because it makes more sense conceptually.
