### ISSUE TITLE
Duplicate ID checking

### ISSUE THREAD

**Issue by JoshDreamland** [IsmAvatar/LateralGM#82]
We just got done sorting the problem your mother told you about, and the cause turned out to be two instances in a room with the same ID.

I have no idea as to how this happened and no steps to reproduce, so rather than whine at you to fix the undiagnosable, I'd like to request a feature wherein the IDE double-checks IDs for duplicates, either on room load, game load, or some triggerable event (preferably one that the ENIGMA plugin can fire, especially upon learning that these duplicates exist).

This issue can be assigned low-priority, as it is simple to detect, impossible to reproduce, and easy to work around: running the existing "defrag IDs" feature solves it.

**Comment by RobertBColton** [comment]
This could possibly be implemented with the missing menu feature "Verify Names" which could also check for ID inconsistencies and alert the user to them as a preliminary step before "Defrag Ids" @JoshDreamland

**Comment by RobertBColton** [comment]
Ok, so working on this, I managed to get a fully working version. It has complexity o(n!) and displays a dialog for each duplicate encountered, prompting the user to change it. When assigning a new id it just gives the duplicate an id at the end of the list since it doesn't know where there are any gaps in the ids. I want to ask you for clarity on this feature request, because this actually seems like a worse way to deal with duplicates since the ids are inflated whereas defrag ids will make them all contiguous. Are you just looking for confirmation of whether there are in fact duplicates before you defrag ids? If so, then this feature will do it for you, and it will do it for you faster because it has o(n!) complexity instead of o(n) complexity like defrag ids.

**Comment by JoshDreamland** [comment]
I doubt your code has complexity `n!`, but even `n²` is too much for this problem. Just make a MultiMap of id/name to resource, then iterate the multimap and complain on any key that has multiple values.

**Comment by RobertBColton** [comment]
Alright I am closing as resolved, the feature has been implemented in #346

Duplicate id checking now happens every time you open a project, and it's efficient too.

**Comment by RobertBColton** [comment]
"Check Names" has been implemented now as well:
https://github.com/IsmAvatar/LateralGM/pull/347
